server:
  port: 7070
spring:
   mvc:
     pathmatch:
         matching-strategy: ANT_PATH_MATCHER
         
   datasource:
    url: jdbc:Mysql://localhost:3306/olxApp
    username: root
    password: root
   jpa:
    hibernate:
     ddl-auto: create
    properties:   
     hibernate:
      format_sql: true
      show_sql: true
management:
  endpoints:
      web:
       exposure: 
         include:
         - "*"
       base-path: "/my-actuator"
       
  endpoint:
       shutdown: 
          enabled: false
            